# Generated by Django 5.0.6 on 2024-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='porter/')),
                ('hall', models.TextField()),
            ],
        ),
    ]
